Course App in React and Spring Boot:

Creating Table:
---------------
CREATE TABLE course(
    course_id NUMBER(20) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1000 MAXVALUE 99999999999999999999 INCREMENT BY 1 START WITH 975639 NOT NULL ENABLE,
    course_name VARCHAR2(50) NOT NULL,
	course_description VARCHAR2(50) NOT NULL,
	course_image VARCHAR2(8),
    PRIMARY KEY(course_id),
    FOREIGN KEY(course_image) REFERENCES profileImage(image_id)
);

CREATE TABLE profileImage(
    image_id VARCHAR2(8) not null,
    image_name VARCHAR2(50),
    image_path VARCHAR2(100),
    PRIMARY KEY(image_id)
)

ALTER TABLE course
ADD course_image VARCHAR2(8);


Insert into Course(course_id,course_name,course_description) Values (101,'Java Core','This is core java course for beginners');
Insert into Course(course_id,course_name,course_description) Values (102,'Java Advance','This is advance java course for beginners');
Insert into Course(course_id,course_name,course_description) Values (103,'Python','This is Python open source for beginners');
Insert into Course(course_id,course_name,course_description) Values (104,'Angular 2','This is UI course in Angular');
Insert into Course(course_id,course_name,course_description) Values (105,'React','This is UI course in React');

commit;

insert into profileimage(image_id,image_name,image_path) VALUES ('ABC123','amir.jpg','C:/Java/image');
insert into profileimage(image_id,image_name,image_path) VALUES ('XYZ456','adil.jpg','C:/Java/image');
insert into profileimage(image_id,image_name,image_path) VALUES ('PQR786','zakiya.jpg','C:/Java/image');
commit;

SELECT
  order_id,
  status,
  first_name,
  last_name
FROM
  orders
LEFT JOIN employees ON employee_id = salesman_id
ORDER BY
  order_date DESC;


SELECT * FROM course
INNER JOIN profileimage
ON course_image = image_id;

ALTER TABLE course
MODIFY COLUMN course_id NUMERIC auto_increment;
